---
# Main MariaDB installation and configuration tasks
- name: Set MariaDB related package names for Debian
  ansible.builtin.set_fact:
    mariadb_pkg: mariadb-server
    mariadb_client: mariadb-client
    mariadb_pymysql: python3-pymysql
  when: ansible_os_family == 'Debian'

- name: Set MariaDB related package names for RedHat
  ansible.builtin.set_fact:
    mariadb_pkg: mariadb-server
    mariadb_client: mariadb
    mariadb_pymysql: python3-PyMySQL
  when: ansible_os_family == 'RedHat'

- name: Install MariaDB server and related packages
  ansible.builtin.package:
    name:
      - "{{ mariadb_pkg }}"
      - "{{ mariadb_client }}"
      - "{{ mariadb_pymysql }}"
    state: present
    update_cache: true
  become: true

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: "{{ 'mariadb' if ansible_os_family == 'Debian' else 'mariadb' }}"
    state: started
    enabled: true
  become: true

- name: Check if root password is already set
  ansible.builtin.shell: |
    mysql -u root -p{{ root_pwd }} -e "SELECT 1;"
  register: root_pwd_check
  #ignore_errors: true
  changed_when: false

- name: Try root login with no password
  ansible.builtin.shell: |
    mysql -u root -e "SELECT 1;"
  register: root_nopwd_check
  #ignore_errors: true
  changed_when: false
  when: root_pwd_check.rc != 0

- name: Set root password
  community.mysql.mysql_user:
    name: root
    host: "localhost"
    password: "{{ root_pwd }}"
    column_case_sensitive: true
    update_password: "always"
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
    check_implicit_admin: true
  become: true
  when: root_pwd_check.rc != 0 and (root_nopwd_check is not defined or root_nopwd_check.rc == 0)

- name: Remove the test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ root_pwd }}"
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
  become: true

- name: Ensure anonymous users are not in the database
  community.mysql.mysql_user:
    name: ""
    host: "localhost"
    state: absent
    login_user: root
    login_password: "{{ root_pwd }}"
    column_case_sensitive: true
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ root_pwd }}"
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
  become: true

- name: Create power user
  community.mysql.mysql_user:
    name: "{{ power_user }}"
    password: "{{ pu_pwd }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: "%"
    column_case_sensitive: true
    state: present
    login_user: root
    login_password: "{{ root_pwd }}"
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
  become: true

- name: Check if SQL Script template exists
  ansible.builtin.stat:
    path: "{{ sql_script_path }}"
  register: sql_template_stat

- name: Copy custom SQL scripts (if any)
  ansible.builtin.template:
    src: "{{ sql_script_path }}"
    dest: /tmp/custom_sql_script.sql
    mode: '0664'
  become: true
  when: sql_template_stat.stat.exists

- name: Run custom SQL script (if present)
  community.mysql.mysql_db:
    name: all
    state: import
    target: /tmp/custom_sql_script.sql
    login_user: root
    login_password: "{{ root_pwd }}"
    login_unix_socket: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
  become: true
  when: sql_template_stat.stat.exists
