---
- name: "Verify gcloud installation in Podman container {{ lookup('ansible.builtin.env', 'MOLECULE_CONTAINER_NAME') }}"
  hosts: all
  tasks:

    - name: Run Podman container and execute gcloud command
      ansible.builtin.command:
        cmd: mysql --version
      register: mariadb_version_output
      changed_when: false                          # Prevent marking this task as changed
      failed_when: mariadb_version_output.rc != 0   # Mark as failure if command exits non-zero

    - name: Assert mariadb command mariadb_version_output
      ansible.builtin.assert:
        that:
          - "'Mariadb' in mariadb_version_output.stdout"
          - "'sql' in mariadb_version_output.stdout"
          - mariadb_version_output.rc == 0
        fail_msg: "mariadb command failed or --version output is incorrect."
